/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodeRouteImport } from './routes/$code'
import { Route as ApiPublicAgentCodeRouteImport } from './routes/api/public/agent/$code'
import { Route as ApiPublicRelayCodePollRouteImport } from './routes/api/public/relay/$code/poll'
import { Route as ApiPublicRelayCodeRespondRouteImport } from './routes/api/public/relay/$code/respond'
import { Route as ApiPublicSiteCodeSplatRouteImport } from './routes/api/public/site/$code/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentCodeRoute = ApiPublicAgentCodeRouteImport.update({
  id: '/api/public/agent/$code',
  path: '/api/public/agent/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRelayCodePollRoute = ApiPublicRelayCodePollRouteImport.update({
  id: '/api/public/relay/$code/poll',
  path: '/api/public/relay/$code/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRelayCodeRespondRoute =
  ApiPublicRelayCodeRespondRouteImport.update({
    id: '/api/public/relay/$code/respond',
    path: '/api/public/relay/$code/respond',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSiteCodeSplatRoute = ApiPublicSiteCodeSplatRouteImport.update({
  id: '/api/public/site/$code/$',
  path: '/api/public/site/$code/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/api/public/agent/$code': typeof ApiPublicAgentCodeRoute
  '/api/public/relay/$code/poll': typeof ApiPublicRelayCodePollRoute
  '/api/public/relay/$code/respond': typeof ApiPublicRelayCodeRespondRoute
  '/api/public/site/$code/$': typeof ApiPublicSiteCodeSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/api/public/agent/$code': typeof ApiPublicAgentCodeRoute
  '/api/public/relay/$code/poll': typeof ApiPublicRelayCodePollRoute
  '/api/public/relay/$code/respond': typeof ApiPublicRelayCodeRespondRoute
  '/api/public/site/$code/$': typeof ApiPublicSiteCodeSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/api/public/agent/$code': typeof ApiPublicAgentCodeRoute
  '/api/public/relay/$code/poll': typeof ApiPublicRelayCodePollRoute
  '/api/public/relay/$code/respond': typeof ApiPublicRelayCodeRespondRoute
  '/api/public/site/$code/$': typeof ApiPublicSiteCodeSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$code'
    | '/api/public/agent/$code'
    | '/api/public/relay/$code/poll'
    | '/api/public/relay/$code/respond'
    | '/api/public/site/$code/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$code'
    | '/api/public/agent/$code'
    | '/api/public/relay/$code/poll'
    | '/api/public/relay/$code/respond'
    | '/api/public/site/$code/$'
  id:
    | '__root__'
    | '/'
    | '/$code'
    | '/api/public/agent/$code'
    | '/api/public/relay/$code/poll'
    | '/api/public/relay/$code/respond'
    | '/api/public/site/$code/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeRoute: typeof CodeRoute
  ApiPublicAgentCodeRoute: typeof ApiPublicAgentCodeRoute
  ApiPublicRelayCodePollRoute: typeof ApiPublicRelayCodePollRoute
  ApiPublicRelayCodeRespondRoute: typeof ApiPublicRelayCodeRespondRoute
  ApiPublicSiteCodeSplatRoute: typeof ApiPublicSiteCodeSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$code': {
      id: '/$code'
      path: '/$code'
      fullPath: '/$code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/$code': {
      id: '/api/public/agent/$code'
      path: '/api/public/agent/$code'
      fullPath: '/api/public/agent/$code'
      preLoaderRoute: typeof ApiPublicAgentCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/relay/$code/poll': {
      id: '/api/public/relay/$code/poll'
      path: '/api/public/relay/$code/poll'
      fullPath: '/api/public/relay/$code/poll'
      preLoaderRoute: typeof ApiPublicRelayCodePollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/relay/$code/respond': {
      id: '/api/public/relay/$code/respond'
      path: '/api/public/relay/$code/respond'
      fullPath: '/api/public/relay/$code/respond'
      preLoaderRoute: typeof ApiPublicRelayCodeRespondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site/$code/$': {
      id: '/api/public/site/$code/$'
      path: '/api/public/site/$code/$'
      fullPath: '/api/public/site/$code/$'
      preLoaderRoute: typeof ApiPublicSiteCodeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeRoute: CodeRoute,
  ApiPublicAgentCodeRoute: ApiPublicAgentCodeRoute,
  ApiPublicRelayCodePollRoute: ApiPublicRelayCodePollRoute,
  ApiPublicRelayCodeRespondRoute: ApiPublicRelayCodeRespondRoute,
  ApiPublicSiteCodeSplatRoute: ApiPublicSiteCodeSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
